# Generated by Django 2.0.1 on 2018-01-18 18:07

from django.db import migrations


def create_subjects(apps, schema_editor):
    Subject = apps.get_model('classroom', 'Subject')
    Subject.objects.create(name='Arts', color='#17a2b8')
    Subject.objects.create(name='Commerce', color='#343a40')
    Subject.objects.create(name='Science', color='#17a2b8')
    Subject.objects.create(name='Maths', color='#007bff')
    Subject.objects.create(name='Technology', color='#343a40')
    Subject.objects.create(name='Philosophy', color='#28a745')
    Subject.objects.create(name='History', color='#ffc107')
    Subject.objects.create(name='Geography', color='#343a40')

class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_subjects),
    ]
